import React, { useState, useEffect, useCallback, useRef } from 'react';
import { Card, Button, Spinner, Alert, Row, Col, Badge, InputGroup, Form, Table, Collapse } from 'react-bootstrap';
import { QRCodeSVG } from 'qrcode.react';
import api from '../../services/api';
import { toast } from 'react-toastify';

const FaturaPage = () => {
    const [statusInfo, setStatusInfo] = useState(null);
    const [historico, setHistorico] = useState([]);
    const [loadingData, setLoadingData] = useState(true);

    const [pagamentoPix, setPagamentoPix] = useState(null);
    const [generating, setGenerating] = useState(false);

    const [selectedPixHistorico, setSelectedPixHistorico] = useState(null);
    
    const hasAutoGenerated = useRef(false);

    // =========================================================================
    // LÓGICA DE CARREGAMENTO BLINDADA CONTRA LOOP INFINITO
    // =========================================================================
    const carregarDados = useCallback(async (silencioso = false) => {
        try {
            if (!silencioso) setLoadingData(true);
            const [statusRes, historicoRes] = await Promise.all([
                api.get('/fatura/status'),
                api.get('/fatura/historico')
            ]);
            
            setStatusInfo(statusRes.data);
            setHistorico(historicoRes.data);

            const faturaPendente = historicoRes.data.find(fat => fat.status === 'PENDENTE');
            const faturaPaga = historicoRes.data.find(fat => fat.status === 'PAGO' && new Date(fat.criado_em).getMonth() === new Date().getMonth());
            const isAtivo = statusRes.data.status_assinatura === 'ATIVO';

            // 🟢 A MÁGICA CONTRA O LOOP ACONTECE AQUI
            setPagamentoPix((prevPix) => {
                // Se a loja está ativa...
                if (isAtivo) {
                    // E existia uma tela de cobrança aberta antes, exibe sucesso e fecha
                    if (prevPix) {
                        toast.success("Pagamento confirmado com sucesso!");
                        setSelectedPixHistorico(null);
                    }
                    return null; // Força a tela de cobrança a sumir
                } else {
                    // Se a loja NÃO está ativa e tem fatura pendente, exibe a cobrança
                    if (faturaPendente && !prevPix) {
                        return faturaPendente;
                    }
                    // Mantém o estado atual
                    return prevPix; 
                }
            });

            // Autogerar fatura se tiver vencido e não houver faturas
            if (!faturaPendente && !faturaPaga && (statusRes.data.status_assinatura === 'VENCIDA' || statusRes.data.status_assinatura === 'TRIAL')) {
                if (!hasAutoGenerated.current) {
                    hasAutoGenerated.current = true;
                    // Chama a API silenciosamente para gerar
                    (async () => {
                        try {
                            const response = await api.post('/fatura/gerar', { metodo: 'PIX' });
                            if (response.data.pix_copia_cola || response.data.url_pagamento) {
                                setPagamentoPix(response.data);
                            }
                        } catch (err) {
                            console.error("Autogeração de fatura falhou", err);
                        }
                    })();
                }
            }

        } catch (err) {
            if (!silencioso) toast.error('Erro ao carregar os dados da assinatura.');
        } finally {
            if (!silencioso) setLoadingData(false);
        }
    }, []); // 🟢 ZERO Dependências. Ele não vai ser recriado!

    const handleGerarFatura = async (silencioso = false) => {
        if (!silencioso) setGenerating(true);
        try {
            const response = await api.post('/fatura/gerar', { metodo: 'PIX' });

            if (response.data.pix_copia_cola || response.data.url_pagamento) {
                setPagamentoPix(response.data);
                if (!silencioso) toast.success(`Fatura gerada com sucesso!`);
                carregarDados(true);
            } else {
                if (!silencioso) toast.error("Erro: A operadora não retornou os dados de pagamento.");
            }
        } catch (err) {
            if (!silencioso) toast.error(err.response?.data?.message || err.message || 'Erro ao gerar a fatura no Mercado Pago.');
        } finally {
            if (!silencioso) setGenerating(false);
        }
    };

    // =========================================================================
    // EFEITOS
    // =========================================================================
    useEffect(() => {
        carregarDados();
    }, [carregarDados]);

    useEffect(() => {
        let interval;
        // Monitora o pagamento a cada 5 segundos apenas se houver cobrança na tela
        if (pagamentoPix || selectedPixHistorico) {
            interval = setInterval(() => {
                carregarDados(true);
            }, 5000);
        }
        return () => clearInterval(interval);
    }, [pagamentoPix, selectedPixHistorico, carregarDados]);

    // =========================================================================
    // FUNÇÕES DE AÇÃO
    // =========================================================================
    const handleCopyPix = (codigo) => {
        if (codigo) {
            navigator.clipboard.writeText(codigo);
            toast.info('Código Pix copiado!');
        }
    };

    const handleVerComprovante = (fatura) => {
        const url = fatura.url_pagamento || fatura.comprovante_url;
        if (url) {
            window.open(url, '_blank');
        } else {
            toast.info(`Pagamento registrado com sucesso! (ID: ${fatura.id})`);
        }
    };

    const handleBaixarComprovante = (fatura) => {
        const url = fatura.url_pagamento || fatura.comprovante_url;
        if (url) {
            const link = document.createElement('a');
            link.href = url;
            link.target = '_blank';
            link.download = `Comprovante_Fatura_${fatura.id}.pdf`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            toast.success("Download iniciado!");
        } else {
            toast.error("Comprovante digital indisponível.");
        }
    };

    const formatarData = (dataString) => {
        if (!dataString) return '--/--/----';
        return new Date(dataString).toLocaleDateString('pt-BR');
    };

    const formatarMoeda = (valor) => {
        return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(valor);
    };

    const hoje = new Date();
    const faturaPagaEsteMes = historico.find(fat => {
        if (fat.status !== 'PAGO') return false;
        const dataCriacao = new Date(fat.criado_em);
        return dataCriacao.getMonth() === hoje.getMonth() && dataCriacao.getFullYear() === hoje.getFullYear();
    });

    if (loadingData) {
        return (
            <div className="d-flex justify-content-center align-items-center" style={{ minHeight: '60vh' }}>
                <Spinner animation="border" variant="secondary" />
            </div>
        );
    }

    let badgeColor = 'secondary';
    if (statusInfo?.status_assinatura === 'ATIVO') badgeColor = 'success';
    if (statusInfo?.status_assinatura === 'TRIAL') badgeColor = 'primary';
    if (['BLOQUEADA', 'VENCIDA'].includes(statusInfo?.status_assinatura)) badgeColor = 'danger';

    const ultimaFatura = historico.length > 0 ? historico[0].valor : null;

    // =========================================================
    // BLOCO DE PAGAMENTO CLEAN (DUAS OPÇÕES LADO A LADO)
    // =========================================================
    const PaymentBlock = ({ data }) => (
        <div className="w-100 animate__animated animate__fadeIn">
            <h6 className="fw-bold text-dark mb-3 text-center">Fatura Gerada. Escolha como pagar:</h6>
            
            <Row className="g-3 justify-content-center">
                {/* OPÇÃO 1: PIX DIRETO */}
                <Col md={12} xl={6}>
                    <div className="bg-light p-3 rounded-4 border shadow-sm h-100 d-flex flex-column align-items-center justify-content-center">
                        <div className="d-flex align-items-center mb-2">
                            <i className="bi bi-lightning-charge-fill text-success fs-5 me-2"></i>
                            <span className="fw-bold text-dark">Pagamento via PIX</span>
                        </div>
                        
                        {data.pix_copia_cola ? (
                            <>
                                <div className="bg-white p-2 rounded-3 shadow-sm mb-3">
                                    <QRCodeSVG value={data.pix_copia_cola} size={130} />
                                </div>
                                <InputGroup size="sm" className="w-100 mt-auto">
                                    <Form.Control
                                        value={data.pix_copia_cola}
                                        readOnly
                                        className="bg-white text-muted font-monospace"
                                        style={{ fontSize: '0.75rem' }}
                                    />
                                    <Button variant="dark" onClick={() => handleCopyPix(data.pix_copia_cola)} className="fw-medium px-3">
                                        Copiar
                                    </Button>
                                </InputGroup>
                            </>
                        ) : (
                            <span className="text-muted small my-auto">Código PIX indisponível.</span>
                        )}
                    </div>
                </Col>

                {/* OPÇÃO 2: BOLETO / CHECKOUT MERCADO PAGO */}
                <Col md={12} xl={6}>
                    <div className="bg-light p-4 rounded-4 border shadow-sm h-100 d-flex flex-column align-items-center justify-content-center text-center">
                        <div className="d-flex align-items-center mb-3">
                            <i className="bi bi-shield-lock text-primary fs-4 me-2"></i>
                            <span className="fw-bold text-dark">Link Seguro</span>
                        </div>
                        <p className="text-muted small mb-4">
                            Acesse o ambiente seguro do Mercado Pago para visualizar sua fatura detalhada.
                        </p>
                        
                        {data.url_pagamento ? (
                            <a
                                href={data.url_pagamento}
                                target="_blank"
                                rel="noreferrer"
                                className="btn btn-outline-primary rounded-pill px-4 py-2 fw-medium w-100 mt-auto"
                            >
                                <i className="bi bi-box-arrow-up-right me-2"></i> Abrir Fatura
                            </a>
                        ) : (
                            <span className="text-muted small my-auto">Link indisponível.</span>
                        )}
                    </div>
                </Col>
            </Row>

            <div className="d-flex align-items-center justify-content-center mt-4 text-secondary small">
                <Spinner animation="border" size="sm" className="me-2 text-primary opacity-75" />
                <span>Aguardando a confirmação do Mercado Pago...</span>
            </div>
        </div>
    );

    return (
        <div className="container-fluid p-0 pb-5" style={{ maxWidth: '1100px', margin: '0 auto' }}>
            <div className="mb-4 px-3 px-md-0 pt-3 pt-md-0">
                <h4 className="fw-bold text-dark mb-1">Minha Assinatura</h4>
                <p className="text-muted small mb-0">Gerencie seu plano, histórico de faturas e pagamentos.</p>
            </div>

            <Row className="g-4 mb-5 px-3 px-md-0">
                {/* COLUNA ESQUERDA: RESUMO CLEAN */}
                <Col lg={5}>
                    <Card className="border-0 shadow-sm rounded-4 h-100">
                        <Card.Body className="p-4 d-flex flex-column">
                            <div className="d-flex justify-content-between align-items-center mb-4 pb-3 border-bottom">
                                <h6 className="fw-bold text-dark mb-0">Resumo do Plano</h6>
                                <Badge bg={badgeColor} className="rounded-pill px-3 py-2 fw-medium" style={{ letterSpacing: '0.5px' }}>
                                    {statusInfo?.status_assinatura || 'DESCONHECIDO'}
                                </Badge>
                            </div>
                            
                            <div className="d-flex flex-column gap-3 mb-4 flex-grow-1">
                                <div className="d-flex justify-content-between align-items-center">
                                    <span className="text-muted small">Plano Atual</span>
                                    <span className="fw-bold text-dark">{statusInfo?.plano || 'Básico'}</span>
                                </div>
                                <div className="d-flex justify-content-between align-items-center">
                                    <span className="text-muted small">Próximo Vencimento</span>
                                    <span className="fw-bold text-dark">{formatarData(statusInfo?.data_vencimento)}</span>
                                </div>
                                <div className="d-flex justify-content-between align-items-center">
                                    <span className="text-muted small">Valor Mensal</span>
                                    <span className="fw-bold text-dark">
                                        {ultimaFatura ? formatarMoeda(ultimaFatura) : '--'}
                                    </span>
                                </div>
                            </div>
                            
                            <div className="mt-auto bg-light rounded-3 p-3 text-center">
                                <span className="small text-muted">
                                    <i className="bi bi-shield-check text-success me-1"></i>
                                    Sua assinatura é renovada automaticamente após o pagamento.
                                </span>
                            </div>
                        </Card.Body>
                    </Card>
                </Col>

                {/* COLUNA DIREITA: AÇÃO DE PAGAMENTO CLEAN */}
                <Col lg={7}>
                    <Card className="border-0 shadow-sm rounded-4 h-100 bg-white">
                        <Card.Body className="p-4 d-flex flex-column justify-content-center align-items-center">
                            
                            {pagamentoPix ? (
                                <PaymentBlock data={pagamentoPix} />
                            ) : (
                                faturaPagaEsteMes ? (
                                    <div className="text-center">
                                        <div className="d-inline-flex align-items-center justify-content-center bg-success bg-opacity-10 text-success rounded-circle mb-3" style={{ width: '64px', height: '64px' }}>
                                            <i className="bi bi-check-lg fs-2"></i>
                                        </div>
                                        <h5 className="fw-bold text-dark mb-1">Assinatura em Dia</h5>
                                        <p className="text-muted small mb-0">Nenhuma pendência financeira encontrada para este período.</p>
                                    </div>
                                ) : (
                                    /* OPÇÃO ÚNICA DE GERAR FATURA */
                                    <div className="text-center w-100">
                                        <div className="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-10 text-primary rounded-circle mb-3" style={{ width: '64px', height: '64px' }}>
                                            <i className="bi bi-file-earmark-text fs-2"></i>
                                        </div>
                                        <h5 className="fw-bold text-dark mb-1">Fatura Disponível</h5>
                                        <p className="text-muted small mb-4">Gere a fatura para acessar as opções de pagamento.</p>
                                        
                                        <Button
                                            variant="dark" 
                                            className="rounded-pill px-5 py-3 fw-medium shadow-sm d-inline-flex align-items-center justify-content-center"
                                            onClick={() => handleGerarFatura(false)} 
                                            disabled={generating}
                                        >
                                            {generating ? <Spinner size="sm" className="me-2" /> : <i className="bi bi-arrow-repeat me-2"></i>}
                                            Gerar Fatura Mensal
                                        </Button>
                                    </div>
                                )
                            )}
                        </Card.Body>
                    </Card>
                </Col>
            </Row>

            {/* HISTÓRICO DE FATURAS CLEAN */}
            <div className="px-3 px-md-0">
                <div className="d-flex align-items-center mb-3">
                    <h6 className="fw-bold text-dark mb-0">Histórico de Pagamentos</h6>
                </div>
                
                <Card className="border-0 shadow-sm rounded-4 overflow-hidden">
                    <Table responsive hover className="mb-0 align-middle table-borderless">
                        <thead className="bg-light">
                            <tr>
                                <th className="py-3 px-4 text-muted fw-semibold small text-uppercase" style={{ fontSize: '0.75rem' }}>Data</th>
                                <th className="py-3 text-muted fw-semibold small text-uppercase" style={{ fontSize: '0.75rem' }}>Descrição</th>
                                <th className="py-3 text-muted fw-semibold small text-uppercase" style={{ fontSize: '0.75rem' }}>Valor</th>
                                <th className="py-3 text-muted fw-semibold small text-uppercase text-center" style={{ fontSize: '0.75rem' }}>Status</th>
                                <th className="py-3 text-muted fw-semibold small text-uppercase text-end px-4" style={{ fontSize: '0.75rem' }}>Ações</th>
                            </tr>
                        </thead>
                        <tbody className="border-top">
                            {historico.length === 0 ? (
                                <tr><td colSpan="5" className="text-center py-5 text-muted small">Nenhuma transação encontrada.</td></tr>
                            ) : (
                                historico.map((fat) => (
                                    <React.Fragment key={fat.id}>
                                        <tr style={{ borderBottom: '1px solid #f1f1f4' }}>
                                            <td className="px-4 py-3 text-dark small">{formatarData(fat.criado_em)}</td>
                                            <td className="py-3 text-muted small">{fat.descricao || 'Mensalidade SaaS'}</td>
                                            <td className="py-3 text-dark fw-medium small">{formatarMoeda(fat.valor)}</td>
                                            <td className="py-3 text-center">
                                                <Badge 
                                                    bg={fat.status === 'PAGO' ? 'success' : fat.status === 'PENDENTE' ? 'warning' : 'danger'} 
                                                    className={`rounded-pill fw-medium px-2 py-1 ${fat.status === 'PENDENTE' ? 'text-dark' : ''}`}
                                                    style={{ fontSize: '0.7rem' }}
                                                >
                                                    {fat.status}
                                                </Badge>
                                            </td>
                                            <td className="py-3 text-end px-4">
                                                {fat.status === 'PAGO' ? (
                                                    <div className="d-flex justify-content-end gap-2">
                                                        <Button variant="light" size="sm" className="text-secondary p-1 border-0" onClick={() => handleVerComprovante(fat)} title="Visualizar Recibo">
                                                            <i className="bi bi-eye"></i>
                                                        </Button>
                                                        <Button variant="light" size="sm" className="text-secondary p-1 border-0" onClick={() => handleBaixarComprovante(fat)} title="Download">
                                                            <i className="bi bi-download"></i>
                                                        </Button>
                                                    </div>
                                                ) : fat.status === 'PENDENTE' ? (
                                                    <Button
                                                        variant="dark" size="sm" className="rounded-3 shadow-sm px-3" style={{ fontSize: '0.75rem' }}
                                                        onClick={() => setSelectedPixHistorico(selectedPixHistorico === fat.id ? null : fat.id)}
                                                    >
                                                        {selectedPixHistorico === fat.id ? 'Esconder' : 'Pagar Fatura'}
                                                    </Button>
                                                ) : (
                                                    <span className="text-muted small opacity-50">-</span>
                                                )}
                                            </td>
                                        </tr>

                                        {/* EXPANSÃO CLEAN DO HISTÓRICO */}
                                        <tr>
                                            <td colSpan="5" className="p-0 border-0">
                                                <Collapse in={selectedPixHistorico === fat.id}>
                                                    <div className="bg-light px-2 py-4 border-bottom">
                                                        {fat.pix_copia_cola || fat.url_pagamento ? (
                                                            <PaymentBlock data={fat} />
                                                        ) : (
                                                            <Alert variant="warning" className="mx-auto border-0 text-center mb-0 small" style={{ maxWidth: '400px' }}>
                                                                Link de pagamento indisponível. Por favor, aguarde o ciclo de faturamento atual.
                                                            </Alert>
                                                        )}
                                                    </div>
                                                </Collapse>
                                            </td>
                                        </tr>
                                    </React.Fragment>
                                ))
                            )}
                        </tbody>
                    </Table>
                </Card>
            </div>
        </div>
    );
};

export default FaturaPage;